### PR TITLE
🐛Fix Datefield

### LINKED ISSUE #12: 🐛Decimal form field no new input after removing old value
#### Describe your issue

When deleting a value from the decimal form field, so that the field is blank.
There is no opportunity to write a new value.

#### How can others reproduce the issue?

1. Add a value into the decimal form field.
1. Remove the value, so that the field is blank.
1. Try to add a new value.

#### What's your setup

- OS : macOS Mojave 10.14.2
- Node : v8.12.0
- NPM : 6.4.1

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by MaFa961**
**Changes:**

1. Add alternativ for datepicker
1. Add check if day is in month
1. Fix NumberInputValidator
1. Default value is --.--.---- for date-form-field
1. Default value is 0.0 for number-form-field
1. Default value is 0 for long-form-field
1. Fix valid input. Only allowed keys are shown in the form-field.

**Issues**

Closes #12 
Known #11 
Known #13 

PR: #10 

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

### CODE REVIEW

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 1]
```diff
@@ -23,11 +24,13 @@ export class DateFormField implements IFormField {
...
   public render(): any {
-    return <div class='form-group'>
-      <label htmlFor={this.formField.id}>{this.formField.label}</label>
-      <input type='text' data-provide='datepicker' class='form-control'
-        id={this.formField.id} value={this.value} onFocus={(event: any): void => this._handleChange(event)} />
-    </div>;
+    return (
+      <div class= 'form-group'>
+        <label htmlFor={this.formField.id}>{this.formField.label}</label>
+        <input type='date' data-provide='datepicker' class='form-control'
```
Comment (roblen45) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: type=date ist not supported by safari browser

File: src/components/usertask-component/form-fields/input_validator.ts [hunk 2]
```diff
@@ -14,4 +14,39 @@ export class InputValidator {
 
     return keyCode >= keyCodeDigitOne;
   }
+
+  public shouldValidateKeyForDate(keyCode: number, value: string): boolean {
```
Comment (roblen45) [inline src/components/usertask-component/form-fields/input_validator.ts]: Create a base class InputValidator with two derived classes DateInputValidator and NumberInputValidator which has a concrete overload for shouldValidateKey

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 3]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
     return this.formField.id;
   }
 
+  private readonly _reg: any = /^\s*(3[01]|[12][0-9]|0?[1-9])\.(1[012]|0?[1-9])\.((?:19|20)\d{2})\s*$/;
```
Comment (roblen45) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: This should be a const.

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 4]
```diff
@@ -1,13 +1,15 @@
...
 
+import {DateInputValidator} from './date_input_validator';
 import {IFormField} from './iform_field';
 
 @Component({
   tag: 'date-form-field',
   styleUrl: 'date-form-field.css',
   shadow: true,
 })
+
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date-form-field.tsx]:
```suggestion
```

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 5]
```diff
@@ -18,19 +20,34 @@ export class DateFormField implements IFormField {
     return this.formField.id;
   }
 
+  // tslint:disable-next-line
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: Why is tslint disabled here?

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 6]
```diff
@@ -0,0 +1,43 @@
+import { InputValidator } from './input_validator';
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]:
```suggestion
import {InputValidator} from './input_validator';
```

File: src/components/usertask-component/form-fields/number_input_validator.ts [hunk 7]
```diff
@@ -0,0 +1,19 @@
+import { InputValidator } from './input_validator';
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/number_input_validator.ts]:
```suggestion
import {InputValidator} from './input_validator';
```

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+  public isValidDate(value: string): boolean {
+    const year: number = parseInt(value.substring(6, 10));
+    const month: number = parseInt(value.substring(3, 5));
+    const day: number = parseInt(value.substring(0, 2));
+
+    return this.isDayInMonth(day, month, year);
+  }
+
+  private isDayInMonth(day: number, month: number, year: number): boolean {
+    const date: any = new Date(year, month, 0).getDate();
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]:
```suggestion
    const numberOfDaysInSelectedMonth: number = new Date(year, month, 0).getDate();
```

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 9]
```diff
@@ -0,0 +1,43 @@
+import { InputValidator } from './input_validator';
+
+export class DateInputValidator extends InputValidator {
+
+  constructor(regex: string) {
+    super(regex);
+  }
+
+  public shouldValidateKey(keyCode: number, value: string): boolean {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]:
```suggestion
  public validateKey(keyCode: number, value: string): boolean {
```

File: src/components/usertask-component/form-fields/date-form-field.tsx (hunk 5 above)
Comment (MaFa961) [reply src/components/usertask-component/form-fields/date-form-field.tsx]: tslint is disabled because of "tslint(max-line-length)". 
Should we put the regex in a new line?

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 10]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
...
   }
 
   private _handleChange(event: any): void {
     this.value = event.target.value;
   }
+
+  private _handleKeyDown(event: any): void {
+    const value: string = this.value + event.key;
+
+    if (!this._inputValidator.validateKey(event.keyCode, event.target.value) && !this._inputValidator.isValid(value)) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date-form-field.tsx]:
```suggestion
    if (!this._inputValidator.validateKey(event.keyCode, event.target.value) &&
        !this._inputValidator.isValid(value)) {
```

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 11]
```diff
@@ -0,0 +1,43 @@
...
+  }
+
+  public validateKey(keyCode: number, value: string): boolean {
+    const keyCodeDigitDot: number = 190;
+    const keyCodeDigitZero: number = 48;
+    const keyCodeDigitNine: number = 57;
+    const keyCodeBackspace: number = 8;
+    const keyCodeEnter: number = 13;
+
+    if (keyCode === keyCodeEnter) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Extract Businessrule

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 12]
```diff
@@ -0,0 +1,43 @@
...
+      return this.isValid(value) && this.isValidDate(value);
+    }
+
+    if (value.length === 2) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Extract Businessrule

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 13]
```diff
@@ -0,0 +1,43 @@
...
+      return keyCode === keyCodeDigitDot || keyCode === keyCodeBackspace;
+    } else if (value.length === 5) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Extract Businessrule

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+    const month: number = parseInt(value.substring(3, 5));
+    const day: number = parseInt(value.substring(0, 2));
+
+    return this.isDayInMonth(day, month, year);
+  }
+
+  private isDayInMonth(day: number, month: number, year: number): boolean {
+    const numberOfDaysInSelectedMonth: number = new Date(year, month, 0).getDate();
+
+    return day <= numberOfDaysInSelectedMonth;
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Extract Businessrule

File: src/components/usertask-component/form-fields/long-form-field.tsx [hunk 15]
```diff
@@ -46,7 +46,7 @@ export class LongFormField implements IFormField {
   private _handleKeyDown(event: any): void {
     const value: string = (this.value) ? this.value + event.key : event.key;
 
-    if (this._inputValidator.shouldValidateKey(event.keyCode) && !this._inputValidator.isValid(value)) {
+    if (this._inputValidator.validateKey(event.keyCode) && !this._inputValidator.isValid(value)) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/long-form-field.tsx]: Extract Businessrule

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 16]
```diff
@@ -48,7 +48,7 @@ export class NumberFormField implements IFormField {
   private _handleKeyDown(event: any): void {
     const value: string = this.value + event.key;
 
-    if (this._inputValidator.shouldValidateKey(event.keyCode) && !this._inputValidator.isValid(value)) {
+    if (this._inputValidator.validateKey(event.keyCode) && !this._inputValidator.isValid(value)) {
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/number-form-field.tsx]: Extract Businessrule

File: src/components/usertask-component/form-fields/date-form-field.tsx (hunk 5 above)
Comment (SteffenKn) [reply src/components/usertask-component/form-fields/date-form-field.tsx]: Imo yes

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 17]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
...
+
+      </div>
+    );
   }
 
   private _handleChange(event: any): void {
     this.value = event.target.value;
   }
+
+  private _handleKeyDown(event: any): void {
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date-form-field.tsx]:
```suggestion
  private _handleKeyDown(event: KeyEvent): void {
```

or something like that

File: src/components/usertask-component/form-fields/number_input_validator.ts [hunk 18]
```diff
@@ -0,0 +1,19 @@
...
+  }
+
+  public isValid(value: string): boolean {
+    return super.isValid(value);
+  }
+
+  public validateKey(keyCode: number): boolean {
+    const keyCodeDigitOne: number = 49;
+
+    return keyCode >= keyCodeDigitOne;
```
Comment (Vyperus) [inline src/components/usertask-component/form-fields/number_input_validator.ts]: Extract Businessrule

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 19]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
...
+        <label htmlFor={this.formField.id}>{this.formField.label}</label>
+        <input type='text' data-provide='datepicker' class='form-control' maxlength='10' placeholder='--.--.----'
+          id={this.formField.id} value={this.value} onFocus={(event: any): void => this._handleChange(event)}
+          onKeyDown={(event: any): void => this._handleKeyDown(event)}></input>
+
+      </div>
+    );
   }
 
   private _handleChange(event: any): void {
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: this event is also not any

File: src/components/usertask-component/form-fields/date-form-field.tsx (hunk 10 above)
Comment (SteffenKn) [reply src/components/usertask-component/form-fields/date-form-field.tsx]: Extract Business Rule

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 20]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
...
     this.value = this.formField.defaultValue;
   }
 
   public render(): any {
-    return <div class='form-group'>
-      <label htmlFor={this.formField.id}>{this.formField.label}</label>
-      <input type='text' data-provide='datepicker' class='form-control'
-        id={this.formField.id} value={this.value} onFocus={(event: any): void => this._handleChange(event)} />
-    </div>;
+    return (
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: IMO you can remove the brackets and then add the return type HTMLDivElement to the method signature

File: src/components/usertask-component/form-fields/date_input_validator.ts (hunk 14 above)
Comment (SteffenKn) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Please move this into a variable and return the variable.

File: src/components/usertask-component/form-fields/input_validator.ts [hunk 21]
```diff
@@ -9,9 +9,10 @@ export class InputValidator {
     return this._regex.test(value);
   }
 
-  public shouldValidateKey(keyCode: number): boolean {
+  public validateKey(keyCode: number, value?: string): boolean {
     const keyCodeDigitOne: number = 49;
 
     return keyCode >= keyCodeDigitOne;
```
Comment (SteffenKn) [inline src/components/usertask-component/form-fields/input_validator.ts]: Please move this into a variable and return the variable (even though you did not add this).

File: src/components/usertask-component/form-fields/long-form-field.tsx (hunk 15 above)
Comment (SteffenKn) [inline src/components/usertask-component/form-fields/long-form-field.tsx]: Extract Business Rule

File: src/components/usertask-component/form-fields/number-form-field.tsx (hunk 16 above)
Comment (SteffenKn) [inline src/components/usertask-component/form-fields/number-form-field.tsx]: Extract Business Rule

File: src/components/usertask-component/form-fields/number_input_validator.ts (hunk 18 above)
Comment (SteffenKn) [inline src/components/usertask-component/form-fields/number_input_validator.ts]: Please move this into a variable and return the variable.

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 22]
```diff
@@ -0,0 +1,43 @@
...
+    const keyCodeDigitNine: number = 57;
+    const keyCodeBackspace: number = 8;
+    const keyCodeEnter: number = 13;
+
+    if (keyCode === keyCodeEnter) {
+      return this.isValid(value) && this.isValidDate(value);
+    }
+
+    if (value.length === 2) {
+      return keyCode === keyCodeDigitDot || keyCode === keyCodeBackspace;
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: Would extract this business rule too, to improve readability

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 23]
```diff
@@ -0,0 +1,43 @@
...
+    } else if (value.length === 5) {
+      return keyCode === keyCodeDigitDot || keyCode === keyCodeBackspace;
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: same here as above

File: src/components/usertask-component/form-fields/date_input_validator.ts [hunk 24]
```diff
@@ -0,0 +1,43 @@
...
+    }
+
+    return (keyCode <= keyCodeDigitNine && keyCode >= keyCodeDigitZero) || keyCode === keyCodeBackspace;
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date_input_validator.ts]: and definitely also here

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 25]
```diff
@@ -48,7 +48,7 @@ export class NumberFormField implements IFormField {
   private _handleKeyDown(event: any): void {
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/number-form-field.tsx]:
```suggestion
  private _handleKeyDown(event: KeyEvent): void {
```

or something like this

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 26]
```diff
@@ -18,19 +19,34 @@ export class DateFormField implements IFormField {
     return this.formField.id;
   }
 
+  // tslint:disable-next-line
+  private readonly _inputValidator: DateInputValidator = new DateInputValidator('/^\s*(3[01]|[12][0-9]|0?[1-9])\.(1[012]|0?[1-9])\.((?:19|20)\d{2})\s*$/');
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/date-form-field.tsx]: _Probably an unpopular Opinion_:

What if we actually create the `DateInputValidator` in the class constructor? 

```TypeScript
private _dateInputValidator: DateInputValidator;
...
constructor() {
   // I'd check, if we also can use a RegExp object here.
   const validatorRegex: string = `/^\s*(3[01]|[12][0-9]|0?[1-9])\.(1[012]|0?[1-9])\.((?:19|20)\d{2})\s*$/`;
   this._inputValidator = new DateInputValidator(validatorRegex);
}
```

File: src/components/usertask-component/form-fields/number_input_validator.ts [hunk 27]
```diff
@@ -0,0 +1,19 @@
+import {InputValidator} from './input_validator';
+
+export class NumberInputValidator extends InputValidator {
+
+  constructor(regex: string) {
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/number_input_validator.ts]: _Not really necessary, but: _
I would expect, that I also can throw `RegExp` objects in here.

File: src/components/usertask-component/form-fields/number-form-field.tsx (hunk 25 above)
Comment (MaFa961) [reply src/components/usertask-component/form-fields/number-form-field.tsx]: I do not find the right type. 
KeyEvent, KeyboardEvent, Event does not work without rewrote everything with `event.*`

Comment (alexanderkasten) [reply src/components/usertask-component/form-fields/number-form-field.tsx]:
```
  private _handleKeyDown(event: KeyboardEvent): void {
    const value: string = this.value + event.key;
    const eventTarget = (event.target as HTMLInputElement);

    const isValidInput: boolean = (!this._inputValidator.validateKey(event.keyCode, eventTarget.value) && !this._inputValidator.isValid(value));

    if (isValidInput) {
      event.preventDefault();
    }
  }
```

File: src/components/usertask-component/form-fields/date-form-field.tsx (hunk 19 above)
Comment (alexanderkasten) [reply src/components/usertask-component/form-fields/date-form-field.tsx]:
```
  private _handleChange(event: FocusEvent): void {
    const eventTarget = (event.target as HTMLInputElement);

    this.value = eventTarget.value;
  }
```

File: src/components/usertask-component/form-fields/date-form-field.tsx (hunk 17 above)
Comment (alexanderkasten) [reply src/components/usertask-component/form-fields/date-form-field.tsx]:
```
  private _handleKeyDown(event: KeyboardEvent): void {
    const value: string = this.value + event.key;
    const eventTarget = (event.target as HTMLInputElement);

    const isValidInput: boolean = (!this._inputValidator.validateKey(event.keyCode, eventTarget.value) && !this._inputValidator.isValid(value));

    if (isValidInput) {
      event.preventDefault();
    }
  }
```

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 28]
```diff
@@ -23,14 +31,25 @@ export class DateFormField implements IFormField {
...
   public render(): any {
-    return <div class='form-group'>
-      <label htmlFor={this.formField.id}>{this.formField.label}</label>
-      <input type='text' data-provide='datepicker' class='form-control'
-        id={this.formField.id} value={this.value} onFocus={(event: any): void => this._handleChange(event)} />
-    </div>;
+    return <div class= 'form-group'>
+              <label htmlFor={this.formField.id}>{this.formField.label}</label>
+              <input type='text' data-provide='datepicker' class='form-control' maxlength='10' placeholder='--.--.----'
+                id={this.formField.id} value={this.value} onFocus={(event: any): void => this._handleChange(event)}
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date-form-field.tsx]:
```suggestion
                id={this.formField.id} value={this.value} onFocus={(event: FocusEvent): void => this._handleChange(event)}
```

File: src/components/usertask-component/form-fields/date-form-field.tsx [hunk 29]
```diff
@@ -23,14 +31,25 @@ export class DateFormField implements IFormField {
...
+                onKeyDown={(event: any): void => this._handleKeyDown(event)}></input>
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/date-form-field.tsx]:
```suggestion
                onKeyDown={(event: KeyboardEvent): void => this._handleKeyDown(event)}></input>
```

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 30]
```diff
@@ -15,24 +15,27 @@ export class NumberFormField implements IFormField {
...
-      <div class='form-group'>
-        <label>{this.formField.label}</label>
-        <input type='text' class='form-control' id={this.formField.id} name={this.formField.label} value={this.value}
-          onKeyDown={(event: any): void => this._handleKeyDown(event)} onInput={(event: any): void => this._handleInput(event)}></input>
-      </div>
-    );
+    return <div class='form-group'>
+              <label>{this.formField.label}</label>
+              <input type='text' class='form-control' id={this.formField.id} name={this.formField.label} value={this.value}
+                onKeyDown={(event: any): void => this._handleKeyDown(event)} onInput={(event: any): void => this._handleInput(event)}></input>
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/number-form-field.tsx]:
```suggestion
                onKeyDown={(event: KeyboardEvent): void => this._handleKeyDown(event)} onInput={(event: KeyboardEvent): void => this._handleInput(event)}></input>
```

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 31]
```diff
@@ -15,24 +15,27 @@ export class NumberFormField implements IFormField {
...
+            </div>;
   }
 
   private _handleInput(event: any): void {
```
Comment (alexanderkasten) [inline src/components/usertask-component/form-fields/number-form-field.tsx]:
```suggestion
  private _handleInput(event: KeyboardEvent): void {
```

or just:
```
  private _handleInput(event: KeyboardEvent): void {
    const eventTarget = (event.target as HTMLInputElement);
    const value: string = eventTarget.value;

    if (this._inputValidator.isValid(value)) {
      this.value = parseFloat(value.replace(',', '.'));
    } else {
      event.preventDefault();
    }
  }
```

File: src/components/usertask-component/form-fields/number-form-field.tsx (hunk 25 above)
Comment (alexanderkasten) [reply src/components/usertask-component/form-fields/number-form-field.tsx]:
```suggestion
  private _handleKeyDown(event: KeyboardEvent): void {
```

File: src/components/usertask-component/form-fields/long-form-field.tsx [hunk 32]
```diff
@@ -15,24 +15,27 @@ export class LongFormField implements IFormField {
 
   public formField: DataModels.UserTasks.UserTaskFormField;
 
+  private readonly _inputValidator: NumberInputValidator;
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/long-form-field.tsx]:
```suggestion
  private readonly _numberInputValidator: NumberInputValidator;
```

File: src/components/usertask-component/form-fields/long-form-field.tsx [hunk 33]
```diff
@@ -15,24 +15,27 @@ export class LongFormField implements IFormField {
...
+
+  constructor() {
+    this._inputValidator = new NumberInputValidator();
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/long-form-field.tsx]: If you look at the definition of this variable, it's defined as `readonly`. Is it really possible to kinda _one time assign_ such a variable? (Since everything is transpiled to JS, it technically should not be a problem, but I would at least expect the TypeScript transpiler to throw its hands in the air). 

Anyways, I would just remove `readonly` from the variable definition.

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 34]
```diff
@@ -15,41 +16,49 @@ export class NumberFormField implements IFormField {
 
   public formField: DataModels.UserTasks.UserTaskFormField;
 
+  private readonly _inputValidator: NumberInputValidator;
+
+  constructor() {
+    this._inputValidator = new NumberInputValidator();
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/number-form-field.tsx]: See above

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 35]
```diff
@@ -15,41 +16,49 @@ export class NumberFormField implements IFormField {
 
   public formField: DataModels.UserTasks.UserTaskFormField;
 
+  private readonly _inputValidator: NumberInputValidator;
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/number-form-field.tsx]:
```suggestion
  private readonly _numberInputValidator: NumberInputValidator;
```

File: src/components/usertask-component/form-fields/number-form-field.tsx [hunk 36]
```diff
@@ -15,41 +16,49 @@ export class NumberFormField implements IFormField {
...
+                placeholder='0.0' value={this.value} pattern='^-?\d+(,|\.)\d+$'
+                onKeyDown={(event: any): void => this._handleKeyDown(event)} onInput={(event: any): void => this._handleInput(event)}></input>
+            </div>;
   }
 
-  private _handleInput(event: any): void {
+  private _handleInput(event: IKeyDownOnInputEvent): void {
     const value: string = event.target.value;
 
+    console.log('NumberField');
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/number-form-field.tsx]: Please remove any `console.log` statements before merging :)

File: src/components/usertask-component/form-fields/number_input_validator.ts [hunk 37]
```diff
@@ -0,0 +1,24 @@
+export class NumberInputValidator {
+
+  public validateKey(keyCode: number): boolean {
+    const keyCodeBackspace: number = 8;
+    const keyCodeDigitZero: number = 48;
+    const keyCodeDigitNine: number = 57;
+    const keyCodeEnter: number = 13;
+    const keyCodeComma: number = 188;
+    const keyCodeDigitDot: number = 190;
```
Comment (robpal94) [inline src/components/usertask-component/form-fields/number_input_validator.ts]: Its probably a big nit-picky, but maybe we could define an `enum` instead of just asiging the different numbers to local constants.
